// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_children
Rcpp::List cpp_children(SEXP x);
RcppExport SEXP _rotio_cpp_children(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_children(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collection_children
Rcpp::List cpp_collection_children(SEXP x);
RcppExport SEXP _rotio_cpp_collection_children(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_collection_children(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collection_set_children
void cpp_collection_set_children(SEXP x, Rcpp::List children);
RcppExport SEXP _rotio_cpp_collection_set_children(SEXP xSEXP, SEXP childrenSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type children(childrenSEXP);
    cpp_collection_set_children(x, children);
    return R_NilValue;
END_RCPP
}
// cpp_collection_clear_children
void cpp_collection_clear_children(SEXP x);
RcppExport SEXP _rotio_cpp_collection_clear_children(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    cpp_collection_clear_children(x);
    return R_NilValue;
END_RCPP
}
// cpp_collection_insert_child
void cpp_collection_insert_child(SEXP x, int index, SEXP child);
RcppExport SEXP _rotio_cpp_collection_insert_child(SEXP xSEXP, SEXP indexSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    cpp_collection_insert_child(x, index, child);
    return R_NilValue;
END_RCPP
}
// cpp_collection_set_child
void cpp_collection_set_child(SEXP x, int index, SEXP child);
RcppExport SEXP _rotio_cpp_collection_set_child(SEXP xSEXP, SEXP indexSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    cpp_collection_set_child(x, index, child);
    return R_NilValue;
END_RCPP
}
// cpp_collection_remove_child
void cpp_collection_remove_child(SEXP x, int index);
RcppExport SEXP _rotio_cpp_collection_remove_child(SEXP xSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    cpp_collection_remove_child(x, index);
    return R_NilValue;
END_RCPP
}
// cpp_append_child
void cpp_append_child(SEXP x, SEXP child);
RcppExport SEXP _rotio_cpp_append_child(SEXP xSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    cpp_append_child(x, child);
    return R_NilValue;
END_RCPP
}
// cpp_insert_child
void cpp_insert_child(SEXP x, int index, SEXP child);
RcppExport SEXP _rotio_cpp_insert_child(SEXP xSEXP, SEXP indexSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    cpp_insert_child(x, index, child);
    return R_NilValue;
END_RCPP
}
// cpp_set_child
void cpp_set_child(SEXP x, int index, SEXP child);
RcppExport SEXP _rotio_cpp_set_child(SEXP xSEXP, SEXP indexSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    cpp_set_child(x, index, child);
    return R_NilValue;
END_RCPP
}
// cpp_remove_child
void cpp_remove_child(SEXP x, int index);
RcppExport SEXP _rotio_cpp_remove_child(SEXP xSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    cpp_remove_child(x, index);
    return R_NilValue;
END_RCPP
}
// cpp_clear_children
void cpp_clear_children(SEXP x);
RcppExport SEXP _rotio_cpp_clear_children(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    cpp_clear_children(x);
    return R_NilValue;
END_RCPP
}
// cpp_set_children
void cpp_set_children(SEXP x, Rcpp::List children);
RcppExport SEXP _rotio_cpp_set_children(SEXP xSEXP, SEXP childrenSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type children(childrenSEXP);
    cpp_set_children(x, children);
    return R_NilValue;
END_RCPP
}
// cpp_index_of_child
int cpp_index_of_child(SEXP x, SEXP child);
RcppExport SEXP _rotio_cpp_index_of_child(SEXP xSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_index_of_child(x, child));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_parent_of
bool cpp_is_parent_of(SEXP x, SEXP other);
RcppExport SEXP _rotio_cpp_is_parent_of(SEXP xSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_parent_of(x, other));
    return rcpp_result_gen;
END_RCPP
}
// cpp_has_child
bool cpp_has_child(SEXP x, SEXP child);
RcppExport SEXP _rotio_cpp_has_child(SEXP xSEXP, SEXP childSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type child(childSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_has_child(x, child));
    return rcpp_result_gen;
END_RCPP
}
// cpp_has_clips
bool cpp_has_clips(SEXP x);
RcppExport SEXP _rotio_cpp_has_clips(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_has_clips(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_find_clips
Rcpp::List cpp_find_clips(SEXP x);
RcppExport SEXP _rotio_cpp_find_clips(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_find_clips(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collection_find_clips
Rcpp::List cpp_collection_find_clips(SEXP x);
RcppExport SEXP _rotio_cpp_collection_find_clips(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_collection_find_clips(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_timeline
SEXP cpp_new_timeline(std::string name, SEXP global_start_time, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_timeline(SEXP nameSEXP, SEXP global_start_timeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type global_start_time(global_start_timeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_timeline(name, global_start_time, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_stack
SEXP cpp_new_stack(std::string name, SEXP source_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_stack(SEXP nameSEXP, SEXP source_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_range(source_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_stack(name, source_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_track
SEXP cpp_new_track(std::string name, SEXP source_range, std::string kind, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_track(SEXP nameSEXP, SEXP source_rangeSEXP, SEXP kindSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_range(source_rangeSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_track(name, source_range, kind, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_clip
SEXP cpp_new_clip(std::string name, SEXP media_reference, SEXP source_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_clip(SEXP nameSEXP, SEXP media_referenceSEXP, SEXP source_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type media_reference(media_referenceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_range(source_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_clip(name, media_reference, source_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_gap
SEXP cpp_new_gap(SEXP duration, std::string name, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_gap(SEXP durationSEXP, SEXP nameSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type duration(durationSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_gap(duration, name, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_transition
SEXP cpp_new_transition(std::string name, std::string transition_type, SEXP in_offset, SEXP out_offset, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_transition(SEXP nameSEXP, SEXP transition_typeSEXP, SEXP in_offsetSEXP, SEXP out_offsetSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type transition_type(transition_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type in_offset(in_offsetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_offset(out_offsetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_transition(name, transition_type, in_offset, out_offset, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_marker
SEXP cpp_new_marker(std::string name, SEXP marked_range, std::string color, SEXP metadata, std::string comment);
RcppExport SEXP _rotio_cpp_new_marker(SEXP nameSEXP, SEXP marked_rangeSEXP, SEXP colorSEXP, SEXP metadataSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type marked_range(marked_rangeSEXP);
    Rcpp::traits::input_parameter< std::string >::type color(colorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    Rcpp::traits::input_parameter< std::string >::type comment(commentSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_marker(name, marked_range, color, metadata, comment));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_effect
SEXP cpp_new_effect(std::string name, std::string effect_name, SEXP metadata, bool enabled);
RcppExport SEXP _rotio_cpp_new_effect(SEXP nameSEXP, SEXP effect_nameSEXP, SEXP metadataSEXP, SEXP enabledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type effect_name(effect_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_effect(name, effect_name, metadata, enabled));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_time_effect
SEXP cpp_new_time_effect(std::string name, std::string effect_name, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_time_effect(SEXP nameSEXP, SEXP effect_nameSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type effect_name(effect_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_time_effect(name, effect_name, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_linear_time_warp
SEXP cpp_new_linear_time_warp(std::string name, std::string effect_name, double time_scalar, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_linear_time_warp(SEXP nameSEXP, SEXP effect_nameSEXP, SEXP time_scalarSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type effect_name(effect_nameSEXP);
    Rcpp::traits::input_parameter< double >::type time_scalar(time_scalarSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_linear_time_warp(name, effect_name, time_scalar, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_freeze_frame
SEXP cpp_new_freeze_frame(std::string name, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_freeze_frame(SEXP nameSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_freeze_frame(name, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_media_reference
SEXP cpp_new_media_reference(std::string name, SEXP available_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_media_reference(SEXP nameSEXP, SEXP available_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_media_reference(name, available_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_external_reference
SEXP cpp_new_external_reference(std::string target_url, SEXP available_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_external_reference(SEXP target_urlSEXP, SEXP available_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type target_url(target_urlSEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_external_reference(target_url, available_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_image_sequence_reference
SEXP cpp_new_image_sequence_reference(std::string target_url_base, std::string name_prefix, std::string name_suffix, int start_frame, int frame_step, double rate, int frame_zero_padding, int missing_frame_policy, SEXP available_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_image_sequence_reference(SEXP target_url_baseSEXP, SEXP name_prefixSEXP, SEXP name_suffixSEXP, SEXP start_frameSEXP, SEXP frame_stepSEXP, SEXP rateSEXP, SEXP frame_zero_paddingSEXP, SEXP missing_frame_policySEXP, SEXP available_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type target_url_base(target_url_baseSEXP);
    Rcpp::traits::input_parameter< std::string >::type name_prefix(name_prefixSEXP);
    Rcpp::traits::input_parameter< std::string >::type name_suffix(name_suffixSEXP);
    Rcpp::traits::input_parameter< int >::type start_frame(start_frameSEXP);
    Rcpp::traits::input_parameter< int >::type frame_step(frame_stepSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type frame_zero_padding(frame_zero_paddingSEXP);
    Rcpp::traits::input_parameter< int >::type missing_frame_policy(missing_frame_policySEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_image_sequence_reference(target_url_base, name_prefix, name_suffix, start_frame, frame_step, rate, frame_zero_padding, missing_frame_policy, available_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_generator_reference
SEXP cpp_new_generator_reference(std::string name, std::string generator_kind, SEXP available_range, SEXP parameters, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_generator_reference(SEXP nameSEXP, SEXP generator_kindSEXP, SEXP available_rangeSEXP, SEXP parametersSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type generator_kind(generator_kindSEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_generator_reference(name, generator_kind, available_range, parameters, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_missing_reference
SEXP cpp_new_missing_reference(std::string name, SEXP available_range, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_missing_reference(SEXP nameSEXP, SEXP available_rangeSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_missing_reference(name, available_range, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_new_serializable_collection
SEXP cpp_new_serializable_collection(std::string name, Rcpp::List children, SEXP metadata);
RcppExport SEXP _rotio_cpp_new_serializable_collection(SEXP nameSEXP, SEXP childrenSEXP, SEXP metadataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< SEXP >::type metadata(metadataSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_new_serializable_collection(name, children, metadata));
    return rcpp_result_gen;
END_RCPP
}
// cpp_effect_name
std::string cpp_effect_name(SEXP x);
RcppExport SEXP _rotio_cpp_effect_name(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_effect_name(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_effect_set_effect_name
void cpp_effect_set_effect_name(SEXP x, std::string effect_name);
RcppExport SEXP _rotio_cpp_effect_set_effect_name(SEXP xSEXP, SEXP effect_nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type effect_name(effect_nameSEXP);
    cpp_effect_set_effect_name(x, effect_name);
    return R_NilValue;
END_RCPP
}
// cpp_effect_enabled
bool cpp_effect_enabled(SEXP x);
RcppExport SEXP _rotio_cpp_effect_enabled(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_effect_enabled(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_effect_set_enabled
void cpp_effect_set_enabled(SEXP x, bool enabled);
RcppExport SEXP _rotio_cpp_effect_set_enabled(SEXP xSEXP, SEXP enabledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    cpp_effect_set_enabled(x, enabled);
    return R_NilValue;
END_RCPP
}
// cpp_ltw_time_scalar
double cpp_ltw_time_scalar(SEXP x);
RcppExport SEXP _rotio_cpp_ltw_time_scalar(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ltw_time_scalar(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ltw_set_time_scalar
void cpp_ltw_set_time_scalar(SEXP x, double time_scalar);
RcppExport SEXP _rotio_cpp_ltw_set_time_scalar(SEXP xSEXP, SEXP time_scalarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type time_scalar(time_scalarSEXP);
    cpp_ltw_set_time_scalar(x, time_scalar);
    return R_NilValue;
END_RCPP
}
// cpp_transition_type
std::string cpp_transition_type(SEXP x);
RcppExport SEXP _rotio_cpp_transition_type(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transition_type(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_transition_set_type
void cpp_transition_set_type(SEXP x, std::string transition_type);
RcppExport SEXP _rotio_cpp_transition_set_type(SEXP xSEXP, SEXP transition_typeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type transition_type(transition_typeSEXP);
    cpp_transition_set_type(x, transition_type);
    return R_NilValue;
END_RCPP
}
// cpp_transition_in_offset
SEXP cpp_transition_in_offset(SEXP x);
RcppExport SEXP _rotio_cpp_transition_in_offset(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transition_in_offset(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_transition_set_in_offset
void cpp_transition_set_in_offset(SEXP x, SEXP in_offset);
RcppExport SEXP _rotio_cpp_transition_set_in_offset(SEXP xSEXP, SEXP in_offsetSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type in_offset(in_offsetSEXP);
    cpp_transition_set_in_offset(x, in_offset);
    return R_NilValue;
END_RCPP
}
// cpp_transition_out_offset
SEXP cpp_transition_out_offset(SEXP x);
RcppExport SEXP _rotio_cpp_transition_out_offset(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transition_out_offset(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_transition_set_out_offset
void cpp_transition_set_out_offset(SEXP x, SEXP out_offset);
RcppExport SEXP _rotio_cpp_transition_set_out_offset(SEXP xSEXP, SEXP out_offsetSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type out_offset(out_offsetSEXP);
    cpp_transition_set_out_offset(x, out_offset);
    return R_NilValue;
END_RCPP
}
// cpp_transition_range_in_parent
SEXP cpp_transition_range_in_parent(SEXP x);
RcppExport SEXP _rotio_cpp_transition_range_in_parent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transition_range_in_parent(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_transition_trimmed_range_in_parent
SEXP cpp_transition_trimmed_range_in_parent(SEXP x);
RcppExport SEXP _rotio_cpp_transition_trimmed_range_in_parent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_transition_trimmed_range_in_parent(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_color
std::string cpp_marker_color(SEXP x);
RcppExport SEXP _rotio_cpp_marker_color(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marker_color(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_set_color
void cpp_marker_set_color(SEXP x, std::string color);
RcppExport SEXP _rotio_cpp_marker_set_color(SEXP xSEXP, SEXP colorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type color(colorSEXP);
    cpp_marker_set_color(x, color);
    return R_NilValue;
END_RCPP
}
// cpp_marker_marked_range
SEXP cpp_marker_marked_range(SEXP x);
RcppExport SEXP _rotio_cpp_marker_marked_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marker_marked_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_set_marked_range
void cpp_marker_set_marked_range(SEXP x, SEXP marked_range);
RcppExport SEXP _rotio_cpp_marker_set_marked_range(SEXP xSEXP, SEXP marked_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type marked_range(marked_rangeSEXP);
    cpp_marker_set_marked_range(x, marked_range);
    return R_NilValue;
END_RCPP
}
// cpp_marker_comment
std::string cpp_marker_comment(SEXP x);
RcppExport SEXP _rotio_cpp_marker_comment(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_marker_comment(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_marker_set_comment
void cpp_marker_set_comment(SEXP x, std::string comment);
RcppExport SEXP _rotio_cpp_marker_set_comment(SEXP xSEXP, SEXP commentSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type comment(commentSEXP);
    cpp_marker_set_comment(x, comment);
    return R_NilValue;
END_RCPP
}
// cpp_visible
bool cpp_visible(SEXP x);
RcppExport SEXP _rotio_cpp_visible(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_visible(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_overlapping
bool cpp_overlapping(SEXP x);
RcppExport SEXP _rotio_cpp_overlapping(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_overlapping(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_parent
SEXP cpp_parent(SEXP x);
RcppExport SEXP _rotio_cpp_parent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_parent(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_duration
SEXP cpp_duration(SEXP x);
RcppExport SEXP _rotio_cpp_duration(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_duration(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_source_range
SEXP cpp_source_range(SEXP x);
RcppExport SEXP _rotio_cpp_source_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_source_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_source_range
void cpp_set_source_range(SEXP x, SEXP source_range);
RcppExport SEXP _rotio_cpp_set_source_range(SEXP xSEXP, SEXP source_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type source_range(source_rangeSEXP);
    cpp_set_source_range(x, source_range);
    return R_NilValue;
END_RCPP
}
// cpp_enabled
bool cpp_enabled(SEXP x);
RcppExport SEXP _rotio_cpp_enabled(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_enabled(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_enabled
void cpp_set_enabled(SEXP x, bool enabled);
RcppExport SEXP _rotio_cpp_set_enabled(SEXP xSEXP, SEXP enabledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    cpp_set_enabled(x, enabled);
    return R_NilValue;
END_RCPP
}
// cpp_available_range
SEXP cpp_available_range(SEXP x);
RcppExport SEXP _rotio_cpp_available_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_available_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_trimmed_range
SEXP cpp_trimmed_range(SEXP x);
RcppExport SEXP _rotio_cpp_trimmed_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_trimmed_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_visible_range
SEXP cpp_visible_range(SEXP x);
RcppExport SEXP _rotio_cpp_visible_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_visible_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_range_in_parent
SEXP cpp_range_in_parent(SEXP x);
RcppExport SEXP _rotio_cpp_range_in_parent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_range_in_parent(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_trimmed_range_in_parent
SEXP cpp_trimmed_range_in_parent(SEXP x);
RcppExport SEXP _rotio_cpp_trimmed_range_in_parent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_trimmed_range_in_parent(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_media_reference
SEXP cpp_clip_media_reference(SEXP x);
RcppExport SEXP _rotio_cpp_clip_media_reference(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clip_media_reference(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_set_media_reference
void cpp_clip_set_media_reference(SEXP x, SEXP media_reference);
RcppExport SEXP _rotio_cpp_clip_set_media_reference(SEXP xSEXP, SEXP media_referenceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type media_reference(media_referenceSEXP);
    cpp_clip_set_media_reference(x, media_reference);
    return R_NilValue;
END_RCPP
}
// cpp_clip_active_media_reference_key
std::string cpp_clip_active_media_reference_key(SEXP x);
RcppExport SEXP _rotio_cpp_clip_active_media_reference_key(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clip_active_media_reference_key(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_set_active_media_reference_key
void cpp_clip_set_active_media_reference_key(SEXP x, std::string key);
RcppExport SEXP _rotio_cpp_clip_set_active_media_reference_key(SEXP xSEXP, SEXP keySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    cpp_clip_set_active_media_reference_key(x, key);
    return R_NilValue;
END_RCPP
}
// cpp_clip_default_media_key
std::string cpp_clip_default_media_key();
RcppExport SEXP _rotio_cpp_clip_default_media_key() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_clip_default_media_key());
    return rcpp_result_gen;
END_RCPP
}
// cpp_mediaref_available_range
SEXP cpp_mediaref_available_range(SEXP x);
RcppExport SEXP _rotio_cpp_mediaref_available_range(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mediaref_available_range(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mediaref_set_available_range
void cpp_mediaref_set_available_range(SEXP x, SEXP available_range);
RcppExport SEXP _rotio_cpp_mediaref_set_available_range(SEXP xSEXP, SEXP available_rangeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type available_range(available_rangeSEXP);
    cpp_mediaref_set_available_range(x, available_range);
    return R_NilValue;
END_RCPP
}
// cpp_mediaref_is_missing_reference
bool cpp_mediaref_is_missing_reference(SEXP x);
RcppExport SEXP _rotio_cpp_mediaref_is_missing_reference(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mediaref_is_missing_reference(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extref_target_url
std::string cpp_extref_target_url(SEXP x);
RcppExport SEXP _rotio_cpp_extref_target_url(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_extref_target_url(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_extref_set_target_url
void cpp_extref_set_target_url(SEXP x, std::string target_url);
RcppExport SEXP _rotio_cpp_extref_set_target_url(SEXP xSEXP, SEXP target_urlSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type target_url(target_urlSEXP);
    cpp_extref_set_target_url(x, target_url);
    return R_NilValue;
END_RCPP
}
// cpp_imgseq_target_url_base
std::string cpp_imgseq_target_url_base(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_target_url_base(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_target_url_base(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_set_target_url_base
void cpp_imgseq_set_target_url_base(SEXP x, std::string v);
RcppExport SEXP _rotio_cpp_imgseq_set_target_url_base(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type v(vSEXP);
    cpp_imgseq_set_target_url_base(x, v);
    return R_NilValue;
END_RCPP
}
// cpp_imgseq_name_prefix
std::string cpp_imgseq_name_prefix(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_name_prefix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_name_prefix(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_name_suffix
std::string cpp_imgseq_name_suffix(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_name_suffix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_name_suffix(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_start_frame
int cpp_imgseq_start_frame(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_start_frame(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_start_frame(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_frame_step
int cpp_imgseq_frame_step(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_frame_step(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_frame_step(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_rate
double cpp_imgseq_rate(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_rate(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_rate(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_frame_zero_padding
int cpp_imgseq_frame_zero_padding(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_frame_zero_padding(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_frame_zero_padding(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_end_frame
int cpp_imgseq_end_frame(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_end_frame(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_end_frame(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_number_of_images_in_sequence
int cpp_imgseq_number_of_images_in_sequence(SEXP x);
RcppExport SEXP _rotio_cpp_imgseq_number_of_images_in_sequence(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_number_of_images_in_sequence(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_frame_for_time
int cpp_imgseq_frame_for_time(SEXP x, SEXP time);
RcppExport SEXP _rotio_cpp_imgseq_frame_for_time(SEXP xSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_frame_for_time(x, time));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_target_url_for_image_number
std::string cpp_imgseq_target_url_for_image_number(SEXP x, int image_number);
RcppExport SEXP _rotio_cpp_imgseq_target_url_for_image_number(SEXP xSEXP, SEXP image_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type image_number(image_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_target_url_for_image_number(x, image_number));
    return rcpp_result_gen;
END_RCPP
}
// cpp_imgseq_presentation_time_for_image_number
SEXP cpp_imgseq_presentation_time_for_image_number(SEXP x, int image_number);
RcppExport SEXP _rotio_cpp_imgseq_presentation_time_for_image_number(SEXP xSEXP, SEXP image_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type image_number(image_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imgseq_presentation_time_for_image_number(x, image_number));
    return rcpp_result_gen;
END_RCPP
}
// cpp_genref_generator_kind
std::string cpp_genref_generator_kind(SEXP x);
RcppExport SEXP _rotio_cpp_genref_generator_kind(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_genref_generator_kind(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_genref_set_generator_kind
void cpp_genref_set_generator_kind(SEXP x, std::string generator_kind);
RcppExport SEXP _rotio_cpp_genref_set_generator_kind(SEXP xSEXP, SEXP generator_kindSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type generator_kind(generator_kindSEXP);
    cpp_genref_set_generator_kind(x, generator_kind);
    return R_NilValue;
END_RCPP
}
// cpp_genref_parameters
SEXP cpp_genref_parameters(SEXP x);
RcppExport SEXP _rotio_cpp_genref_parameters(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_genref_parameters(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_genref_set_parameters
void cpp_genref_set_parameters(SEXP x, SEXP parameters);
RcppExport SEXP _rotio_cpp_genref_set_parameters(SEXP xSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parameters(parametersSEXP);
    cpp_genref_set_parameters(x, parameters);
    return R_NilValue;
END_RCPP
}
// cpp_to_json_string
std::string cpp_to_json_string(SEXP x, int indent);
RcppExport SEXP _rotio_cpp_to_json_string(SEXP xSEXP, SEXP indentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type indent(indentSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_to_json_string(x, indent));
    return rcpp_result_gen;
END_RCPP
}
// cpp_to_json_file
bool cpp_to_json_file(SEXP x, std::string file_name, int indent);
RcppExport SEXP _rotio_cpp_to_json_file(SEXP xSEXP, SEXP file_nameSEXP, SEXP indentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type indent(indentSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_to_json_file(x, file_name, indent));
    return rcpp_result_gen;
END_RCPP
}
// cpp_from_json_string
SEXP cpp_from_json_string(std::string input);
RcppExport SEXP _rotio_cpp_from_json_string(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_from_json_string(input));
    return rcpp_result_gen;
END_RCPP
}
// cpp_from_json_file
SEXP cpp_from_json_file(std::string file_name);
RcppExport SEXP _rotio_cpp_from_json_file(SEXP file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_name(file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_from_json_file(file_name));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clone
SEXP cpp_clone(SEXP x);
RcppExport SEXP _rotio_cpp_clone(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clone(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_schema_name
std::string cpp_schema_name(SEXP x);
RcppExport SEXP _rotio_cpp_schema_name(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_schema_name(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_schema_version
int cpp_schema_version(SEXP x);
RcppExport SEXP _rotio_cpp_schema_version(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_schema_version(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_equivalent_to
bool cpp_is_equivalent_to(SEXP x, SEXP other);
RcppExport SEXP _rotio_cpp_is_equivalent_to(SEXP xSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_equivalent_to(x, other));
    return rcpp_result_gen;
END_RCPP
}
// cpp_is_unknown_schema
bool cpp_is_unknown_schema(SEXP x);
RcppExport SEXP _rotio_cpp_is_unknown_schema(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_unknown_schema(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_name
std::string cpp_name(SEXP x);
RcppExport SEXP _rotio_cpp_name(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_name(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_name
void cpp_set_name(SEXP x, std::string name);
RcppExport SEXP _rotio_cpp_set_name(SEXP xSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    cpp_set_name(x, name);
    return R_NilValue;
END_RCPP
}
// cpp_metadata
SEXP cpp_metadata(SEXP x);
RcppExport SEXP _rotio_cpp_metadata(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_metadata(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_metadata
void cpp_set_metadata(SEXP x, SEXP value);
RcppExport SEXP _rotio_cpp_set_metadata(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    cpp_set_metadata(x, value);
    return R_NilValue;
END_RCPP
}
// cpp_rt_to_seconds
double cpp_rt_to_seconds(SEXP rt);
RcppExport SEXP _rotio_cpp_rt_to_seconds(SEXP rtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_to_seconds(rt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_from_seconds
SEXP cpp_rt_from_seconds(double seconds, double rate);
RcppExport SEXP _rotio_cpp_rt_from_seconds(SEXP secondsSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type seconds(secondsSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_from_seconds(seconds, rate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_to_frames
int cpp_rt_to_frames(SEXP rt);
RcppExport SEXP _rotio_cpp_rt_to_frames(SEXP rtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_to_frames(rt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_from_frames
SEXP cpp_rt_from_frames(double frame, double rate);
RcppExport SEXP _rotio_cpp_rt_from_frames(SEXP frameSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type frame(frameSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_from_frames(frame, rate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_rescaled_to
SEXP cpp_rt_rescaled_to(SEXP rt, double new_rate);
RcppExport SEXP _rotio_cpp_rt_rescaled_to(SEXP rtSEXP, SEXP new_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< double >::type new_rate(new_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_rescaled_to(rt, new_rate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_to_timecode
std::string cpp_rt_to_timecode(SEXP rt, double rate, int drop_frame);
RcppExport SEXP _rotio_cpp_rt_to_timecode(SEXP rtSEXP, SEXP rateSEXP, SEXP drop_frameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type drop_frame(drop_frameSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_to_timecode(rt, rate, drop_frame));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_from_timecode
SEXP cpp_rt_from_timecode(std::string timecode, double rate);
RcppExport SEXP _rotio_cpp_rt_from_timecode(SEXP timecodeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type timecode(timecodeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_from_timecode(timecode, rate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_to_time_string
std::string cpp_rt_to_time_string(SEXP rt);
RcppExport SEXP _rotio_cpp_rt_to_time_string(SEXP rtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_to_time_string(rt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_from_time_string
SEXP cpp_rt_from_time_string(std::string time_string, double rate);
RcppExport SEXP _rotio_cpp_rt_from_time_string(SEXP time_stringSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type time_string(time_stringSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_from_time_string(time_string, rate));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_almost_equal
bool cpp_rt_almost_equal(SEXP a, SEXP b, double delta);
RcppExport SEXP _rotio_cpp_rt_almost_equal(SEXP aSEXP, SEXP bSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_almost_equal(a, b, delta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_add
SEXP cpp_rt_add(SEXP a, SEXP b);
RcppExport SEXP _rotio_cpp_rt_add(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_add(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_subtract
SEXP cpp_rt_subtract(SEXP a, SEXP b);
RcppExport SEXP _rotio_cpp_rt_subtract(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_subtract(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rt_compare
int cpp_rt_compare(SEXP a, SEXP b);
RcppExport SEXP _rotio_cpp_rt_compare(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rt_compare(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_end_time_exclusive
SEXP cpp_tr_end_time_exclusive(SEXP tr);
RcppExport SEXP _rotio_cpp_tr_end_time_exclusive(SEXP trSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_end_time_exclusive(tr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_end_time_inclusive
SEXP cpp_tr_end_time_inclusive(SEXP tr);
RcppExport SEXP _rotio_cpp_tr_end_time_inclusive(SEXP trSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_end_time_inclusive(tr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_extended_by
SEXP cpp_tr_extended_by(SEXP tr, SEXP other);
RcppExport SEXP _rotio_cpp_tr_extended_by(SEXP trSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_extended_by(tr, other));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_clamped_range
SEXP cpp_tr_clamped_range(SEXP tr, SEXP other);
RcppExport SEXP _rotio_cpp_tr_clamped_range(SEXP trSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_clamped_range(tr, other));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_contains_time
bool cpp_tr_contains_time(SEXP tr, SEXP rt);
RcppExport SEXP _rotio_cpp_tr_contains_time(SEXP trSEXP, SEXP rtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rt(rtSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_contains_time(tr, rt));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_contains_range
bool cpp_tr_contains_range(SEXP tr, SEXP other, double epsilon_s);
RcppExport SEXP _rotio_cpp_tr_contains_range(SEXP trSEXP, SEXP otherSEXP, SEXP epsilon_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_s(epsilon_sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_contains_range(tr, other, epsilon_s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_overlaps_range
bool cpp_tr_overlaps_range(SEXP tr, SEXP other, double epsilon_s);
RcppExport SEXP _rotio_cpp_tr_overlaps_range(SEXP trSEXP, SEXP otherSEXP, SEXP epsilon_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_s(epsilon_sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_overlaps_range(tr, other, epsilon_s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_intersects
bool cpp_tr_intersects(SEXP tr, SEXP other, double epsilon_s);
RcppExport SEXP _rotio_cpp_tr_intersects(SEXP trSEXP, SEXP otherSEXP, SEXP epsilon_sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tr(trSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_s(epsilon_sSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_intersects(tr, other, epsilon_s));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tr_range_from_start_end_time
SEXP cpp_tr_range_from_start_end_time(SEXP start_time, SEXP end_time_exclusive);
RcppExport SEXP _rotio_cpp_tr_range_from_start_end_time(SEXP start_timeSEXP, SEXP end_time_exclusiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type end_time_exclusive(end_time_exclusiveSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tr_range_from_start_end_time(start_time, end_time_exclusive));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_tracks
SEXP cpp_timeline_tracks(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_tracks(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_tracks(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_set_tracks
void cpp_timeline_set_tracks(SEXP x, SEXP stack);
RcppExport SEXP _rotio_cpp_timeline_set_tracks(SEXP xSEXP, SEXP stackSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type stack(stackSEXP);
    cpp_timeline_set_tracks(x, stack);
    return R_NilValue;
END_RCPP
}
// cpp_timeline_global_start_time
SEXP cpp_timeline_global_start_time(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_global_start_time(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_global_start_time(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_set_global_start_time
void cpp_timeline_set_global_start_time(SEXP x, SEXP global_start_time);
RcppExport SEXP _rotio_cpp_timeline_set_global_start_time(SEXP xSEXP, SEXP global_start_timeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type global_start_time(global_start_timeSEXP);
    cpp_timeline_set_global_start_time(x, global_start_time);
    return R_NilValue;
END_RCPP
}
// cpp_timeline_duration
SEXP cpp_timeline_duration(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_duration(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_duration(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_video_tracks
Rcpp::List cpp_timeline_video_tracks(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_video_tracks(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_video_tracks(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_audio_tracks
Rcpp::List cpp_timeline_audio_tracks(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_audio_tracks(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_audio_tracks(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_timeline_find_clips
Rcpp::List cpp_timeline_find_clips(SEXP x);
RcppExport SEXP _rotio_cpp_timeline_find_clips(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_timeline_find_clips(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_track_kind
std::string cpp_track_kind(SEXP x);
RcppExport SEXP _rotio_cpp_track_kind(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_track_kind(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_track_set_kind
void cpp_track_set_kind(SEXP x, std::string kind);
RcppExport SEXP _rotio_cpp_track_set_kind(SEXP xSEXP, SEXP kindSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type kind(kindSEXP);
    cpp_track_set_kind(x, kind);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rotio_cpp_children", (DL_FUNC) &_rotio_cpp_children, 1},
    {"_rotio_cpp_collection_children", (DL_FUNC) &_rotio_cpp_collection_children, 1},
    {"_rotio_cpp_collection_set_children", (DL_FUNC) &_rotio_cpp_collection_set_children, 2},
    {"_rotio_cpp_collection_clear_children", (DL_FUNC) &_rotio_cpp_collection_clear_children, 1},
    {"_rotio_cpp_collection_insert_child", (DL_FUNC) &_rotio_cpp_collection_insert_child, 3},
    {"_rotio_cpp_collection_set_child", (DL_FUNC) &_rotio_cpp_collection_set_child, 3},
    {"_rotio_cpp_collection_remove_child", (DL_FUNC) &_rotio_cpp_collection_remove_child, 2},
    {"_rotio_cpp_append_child", (DL_FUNC) &_rotio_cpp_append_child, 2},
    {"_rotio_cpp_insert_child", (DL_FUNC) &_rotio_cpp_insert_child, 3},
    {"_rotio_cpp_set_child", (DL_FUNC) &_rotio_cpp_set_child, 3},
    {"_rotio_cpp_remove_child", (DL_FUNC) &_rotio_cpp_remove_child, 2},
    {"_rotio_cpp_clear_children", (DL_FUNC) &_rotio_cpp_clear_children, 1},
    {"_rotio_cpp_set_children", (DL_FUNC) &_rotio_cpp_set_children, 2},
    {"_rotio_cpp_index_of_child", (DL_FUNC) &_rotio_cpp_index_of_child, 2},
    {"_rotio_cpp_is_parent_of", (DL_FUNC) &_rotio_cpp_is_parent_of, 2},
    {"_rotio_cpp_has_child", (DL_FUNC) &_rotio_cpp_has_child, 2},
    {"_rotio_cpp_has_clips", (DL_FUNC) &_rotio_cpp_has_clips, 1},
    {"_rotio_cpp_find_clips", (DL_FUNC) &_rotio_cpp_find_clips, 1},
    {"_rotio_cpp_collection_find_clips", (DL_FUNC) &_rotio_cpp_collection_find_clips, 1},
    {"_rotio_cpp_new_timeline", (DL_FUNC) &_rotio_cpp_new_timeline, 3},
    {"_rotio_cpp_new_stack", (DL_FUNC) &_rotio_cpp_new_stack, 3},
    {"_rotio_cpp_new_track", (DL_FUNC) &_rotio_cpp_new_track, 4},
    {"_rotio_cpp_new_clip", (DL_FUNC) &_rotio_cpp_new_clip, 4},
    {"_rotio_cpp_new_gap", (DL_FUNC) &_rotio_cpp_new_gap, 3},
    {"_rotio_cpp_new_transition", (DL_FUNC) &_rotio_cpp_new_transition, 5},
    {"_rotio_cpp_new_marker", (DL_FUNC) &_rotio_cpp_new_marker, 5},
    {"_rotio_cpp_new_effect", (DL_FUNC) &_rotio_cpp_new_effect, 4},
    {"_rotio_cpp_new_time_effect", (DL_FUNC) &_rotio_cpp_new_time_effect, 3},
    {"_rotio_cpp_new_linear_time_warp", (DL_FUNC) &_rotio_cpp_new_linear_time_warp, 4},
    {"_rotio_cpp_new_freeze_frame", (DL_FUNC) &_rotio_cpp_new_freeze_frame, 2},
    {"_rotio_cpp_new_media_reference", (DL_FUNC) &_rotio_cpp_new_media_reference, 3},
    {"_rotio_cpp_new_external_reference", (DL_FUNC) &_rotio_cpp_new_external_reference, 3},
    {"_rotio_cpp_new_image_sequence_reference", (DL_FUNC) &_rotio_cpp_new_image_sequence_reference, 10},
    {"_rotio_cpp_new_generator_reference", (DL_FUNC) &_rotio_cpp_new_generator_reference, 5},
    {"_rotio_cpp_new_missing_reference", (DL_FUNC) &_rotio_cpp_new_missing_reference, 3},
    {"_rotio_cpp_new_serializable_collection", (DL_FUNC) &_rotio_cpp_new_serializable_collection, 3},
    {"_rotio_cpp_effect_name", (DL_FUNC) &_rotio_cpp_effect_name, 1},
    {"_rotio_cpp_effect_set_effect_name", (DL_FUNC) &_rotio_cpp_effect_set_effect_name, 2},
    {"_rotio_cpp_effect_enabled", (DL_FUNC) &_rotio_cpp_effect_enabled, 1},
    {"_rotio_cpp_effect_set_enabled", (DL_FUNC) &_rotio_cpp_effect_set_enabled, 2},
    {"_rotio_cpp_ltw_time_scalar", (DL_FUNC) &_rotio_cpp_ltw_time_scalar, 1},
    {"_rotio_cpp_ltw_set_time_scalar", (DL_FUNC) &_rotio_cpp_ltw_set_time_scalar, 2},
    {"_rotio_cpp_transition_type", (DL_FUNC) &_rotio_cpp_transition_type, 1},
    {"_rotio_cpp_transition_set_type", (DL_FUNC) &_rotio_cpp_transition_set_type, 2},
    {"_rotio_cpp_transition_in_offset", (DL_FUNC) &_rotio_cpp_transition_in_offset, 1},
    {"_rotio_cpp_transition_set_in_offset", (DL_FUNC) &_rotio_cpp_transition_set_in_offset, 2},
    {"_rotio_cpp_transition_out_offset", (DL_FUNC) &_rotio_cpp_transition_out_offset, 1},
    {"_rotio_cpp_transition_set_out_offset", (DL_FUNC) &_rotio_cpp_transition_set_out_offset, 2},
    {"_rotio_cpp_transition_range_in_parent", (DL_FUNC) &_rotio_cpp_transition_range_in_parent, 1},
    {"_rotio_cpp_transition_trimmed_range_in_parent", (DL_FUNC) &_rotio_cpp_transition_trimmed_range_in_parent, 1},
    {"_rotio_cpp_marker_color", (DL_FUNC) &_rotio_cpp_marker_color, 1},
    {"_rotio_cpp_marker_set_color", (DL_FUNC) &_rotio_cpp_marker_set_color, 2},
    {"_rotio_cpp_marker_marked_range", (DL_FUNC) &_rotio_cpp_marker_marked_range, 1},
    {"_rotio_cpp_marker_set_marked_range", (DL_FUNC) &_rotio_cpp_marker_set_marked_range, 2},
    {"_rotio_cpp_marker_comment", (DL_FUNC) &_rotio_cpp_marker_comment, 1},
    {"_rotio_cpp_marker_set_comment", (DL_FUNC) &_rotio_cpp_marker_set_comment, 2},
    {"_rotio_cpp_visible", (DL_FUNC) &_rotio_cpp_visible, 1},
    {"_rotio_cpp_overlapping", (DL_FUNC) &_rotio_cpp_overlapping, 1},
    {"_rotio_cpp_parent", (DL_FUNC) &_rotio_cpp_parent, 1},
    {"_rotio_cpp_duration", (DL_FUNC) &_rotio_cpp_duration, 1},
    {"_rotio_cpp_source_range", (DL_FUNC) &_rotio_cpp_source_range, 1},
    {"_rotio_cpp_set_source_range", (DL_FUNC) &_rotio_cpp_set_source_range, 2},
    {"_rotio_cpp_enabled", (DL_FUNC) &_rotio_cpp_enabled, 1},
    {"_rotio_cpp_set_enabled", (DL_FUNC) &_rotio_cpp_set_enabled, 2},
    {"_rotio_cpp_available_range", (DL_FUNC) &_rotio_cpp_available_range, 1},
    {"_rotio_cpp_trimmed_range", (DL_FUNC) &_rotio_cpp_trimmed_range, 1},
    {"_rotio_cpp_visible_range", (DL_FUNC) &_rotio_cpp_visible_range, 1},
    {"_rotio_cpp_range_in_parent", (DL_FUNC) &_rotio_cpp_range_in_parent, 1},
    {"_rotio_cpp_trimmed_range_in_parent", (DL_FUNC) &_rotio_cpp_trimmed_range_in_parent, 1},
    {"_rotio_cpp_clip_media_reference", (DL_FUNC) &_rotio_cpp_clip_media_reference, 1},
    {"_rotio_cpp_clip_set_media_reference", (DL_FUNC) &_rotio_cpp_clip_set_media_reference, 2},
    {"_rotio_cpp_clip_active_media_reference_key", (DL_FUNC) &_rotio_cpp_clip_active_media_reference_key, 1},
    {"_rotio_cpp_clip_set_active_media_reference_key", (DL_FUNC) &_rotio_cpp_clip_set_active_media_reference_key, 2},
    {"_rotio_cpp_clip_default_media_key", (DL_FUNC) &_rotio_cpp_clip_default_media_key, 0},
    {"_rotio_cpp_mediaref_available_range", (DL_FUNC) &_rotio_cpp_mediaref_available_range, 1},
    {"_rotio_cpp_mediaref_set_available_range", (DL_FUNC) &_rotio_cpp_mediaref_set_available_range, 2},
    {"_rotio_cpp_mediaref_is_missing_reference", (DL_FUNC) &_rotio_cpp_mediaref_is_missing_reference, 1},
    {"_rotio_cpp_extref_target_url", (DL_FUNC) &_rotio_cpp_extref_target_url, 1},
    {"_rotio_cpp_extref_set_target_url", (DL_FUNC) &_rotio_cpp_extref_set_target_url, 2},
    {"_rotio_cpp_imgseq_target_url_base", (DL_FUNC) &_rotio_cpp_imgseq_target_url_base, 1},
    {"_rotio_cpp_imgseq_set_target_url_base", (DL_FUNC) &_rotio_cpp_imgseq_set_target_url_base, 2},
    {"_rotio_cpp_imgseq_name_prefix", (DL_FUNC) &_rotio_cpp_imgseq_name_prefix, 1},
    {"_rotio_cpp_imgseq_name_suffix", (DL_FUNC) &_rotio_cpp_imgseq_name_suffix, 1},
    {"_rotio_cpp_imgseq_start_frame", (DL_FUNC) &_rotio_cpp_imgseq_start_frame, 1},
    {"_rotio_cpp_imgseq_frame_step", (DL_FUNC) &_rotio_cpp_imgseq_frame_step, 1},
    {"_rotio_cpp_imgseq_rate", (DL_FUNC) &_rotio_cpp_imgseq_rate, 1},
    {"_rotio_cpp_imgseq_frame_zero_padding", (DL_FUNC) &_rotio_cpp_imgseq_frame_zero_padding, 1},
    {"_rotio_cpp_imgseq_end_frame", (DL_FUNC) &_rotio_cpp_imgseq_end_frame, 1},
    {"_rotio_cpp_imgseq_number_of_images_in_sequence", (DL_FUNC) &_rotio_cpp_imgseq_number_of_images_in_sequence, 1},
    {"_rotio_cpp_imgseq_frame_for_time", (DL_FUNC) &_rotio_cpp_imgseq_frame_for_time, 2},
    {"_rotio_cpp_imgseq_target_url_for_image_number", (DL_FUNC) &_rotio_cpp_imgseq_target_url_for_image_number, 2},
    {"_rotio_cpp_imgseq_presentation_time_for_image_number", (DL_FUNC) &_rotio_cpp_imgseq_presentation_time_for_image_number, 2},
    {"_rotio_cpp_genref_generator_kind", (DL_FUNC) &_rotio_cpp_genref_generator_kind, 1},
    {"_rotio_cpp_genref_set_generator_kind", (DL_FUNC) &_rotio_cpp_genref_set_generator_kind, 2},
    {"_rotio_cpp_genref_parameters", (DL_FUNC) &_rotio_cpp_genref_parameters, 1},
    {"_rotio_cpp_genref_set_parameters", (DL_FUNC) &_rotio_cpp_genref_set_parameters, 2},
    {"_rotio_cpp_to_json_string", (DL_FUNC) &_rotio_cpp_to_json_string, 2},
    {"_rotio_cpp_to_json_file", (DL_FUNC) &_rotio_cpp_to_json_file, 3},
    {"_rotio_cpp_from_json_string", (DL_FUNC) &_rotio_cpp_from_json_string, 1},
    {"_rotio_cpp_from_json_file", (DL_FUNC) &_rotio_cpp_from_json_file, 1},
    {"_rotio_cpp_clone", (DL_FUNC) &_rotio_cpp_clone, 1},
    {"_rotio_cpp_schema_name", (DL_FUNC) &_rotio_cpp_schema_name, 1},
    {"_rotio_cpp_schema_version", (DL_FUNC) &_rotio_cpp_schema_version, 1},
    {"_rotio_cpp_is_equivalent_to", (DL_FUNC) &_rotio_cpp_is_equivalent_to, 2},
    {"_rotio_cpp_is_unknown_schema", (DL_FUNC) &_rotio_cpp_is_unknown_schema, 1},
    {"_rotio_cpp_name", (DL_FUNC) &_rotio_cpp_name, 1},
    {"_rotio_cpp_set_name", (DL_FUNC) &_rotio_cpp_set_name, 2},
    {"_rotio_cpp_metadata", (DL_FUNC) &_rotio_cpp_metadata, 1},
    {"_rotio_cpp_set_metadata", (DL_FUNC) &_rotio_cpp_set_metadata, 2},
    {"_rotio_cpp_rt_to_seconds", (DL_FUNC) &_rotio_cpp_rt_to_seconds, 1},
    {"_rotio_cpp_rt_from_seconds", (DL_FUNC) &_rotio_cpp_rt_from_seconds, 2},
    {"_rotio_cpp_rt_to_frames", (DL_FUNC) &_rotio_cpp_rt_to_frames, 1},
    {"_rotio_cpp_rt_from_frames", (DL_FUNC) &_rotio_cpp_rt_from_frames, 2},
    {"_rotio_cpp_rt_rescaled_to", (DL_FUNC) &_rotio_cpp_rt_rescaled_to, 2},
    {"_rotio_cpp_rt_to_timecode", (DL_FUNC) &_rotio_cpp_rt_to_timecode, 3},
    {"_rotio_cpp_rt_from_timecode", (DL_FUNC) &_rotio_cpp_rt_from_timecode, 2},
    {"_rotio_cpp_rt_to_time_string", (DL_FUNC) &_rotio_cpp_rt_to_time_string, 1},
    {"_rotio_cpp_rt_from_time_string", (DL_FUNC) &_rotio_cpp_rt_from_time_string, 2},
    {"_rotio_cpp_rt_almost_equal", (DL_FUNC) &_rotio_cpp_rt_almost_equal, 3},
    {"_rotio_cpp_rt_add", (DL_FUNC) &_rotio_cpp_rt_add, 2},
    {"_rotio_cpp_rt_subtract", (DL_FUNC) &_rotio_cpp_rt_subtract, 2},
    {"_rotio_cpp_rt_compare", (DL_FUNC) &_rotio_cpp_rt_compare, 2},
    {"_rotio_cpp_tr_end_time_exclusive", (DL_FUNC) &_rotio_cpp_tr_end_time_exclusive, 1},
    {"_rotio_cpp_tr_end_time_inclusive", (DL_FUNC) &_rotio_cpp_tr_end_time_inclusive, 1},
    {"_rotio_cpp_tr_extended_by", (DL_FUNC) &_rotio_cpp_tr_extended_by, 2},
    {"_rotio_cpp_tr_clamped_range", (DL_FUNC) &_rotio_cpp_tr_clamped_range, 2},
    {"_rotio_cpp_tr_contains_time", (DL_FUNC) &_rotio_cpp_tr_contains_time, 2},
    {"_rotio_cpp_tr_contains_range", (DL_FUNC) &_rotio_cpp_tr_contains_range, 3},
    {"_rotio_cpp_tr_overlaps_range", (DL_FUNC) &_rotio_cpp_tr_overlaps_range, 3},
    {"_rotio_cpp_tr_intersects", (DL_FUNC) &_rotio_cpp_tr_intersects, 3},
    {"_rotio_cpp_tr_range_from_start_end_time", (DL_FUNC) &_rotio_cpp_tr_range_from_start_end_time, 2},
    {"_rotio_cpp_timeline_tracks", (DL_FUNC) &_rotio_cpp_timeline_tracks, 1},
    {"_rotio_cpp_timeline_set_tracks", (DL_FUNC) &_rotio_cpp_timeline_set_tracks, 2},
    {"_rotio_cpp_timeline_global_start_time", (DL_FUNC) &_rotio_cpp_timeline_global_start_time, 1},
    {"_rotio_cpp_timeline_set_global_start_time", (DL_FUNC) &_rotio_cpp_timeline_set_global_start_time, 2},
    {"_rotio_cpp_timeline_duration", (DL_FUNC) &_rotio_cpp_timeline_duration, 1},
    {"_rotio_cpp_timeline_video_tracks", (DL_FUNC) &_rotio_cpp_timeline_video_tracks, 1},
    {"_rotio_cpp_timeline_audio_tracks", (DL_FUNC) &_rotio_cpp_timeline_audio_tracks, 1},
    {"_rotio_cpp_timeline_find_clips", (DL_FUNC) &_rotio_cpp_timeline_find_clips, 1},
    {"_rotio_cpp_track_kind", (DL_FUNC) &_rotio_cpp_track_kind, 1},
    {"_rotio_cpp_track_set_kind", (DL_FUNC) &_rotio_cpp_track_set_kind, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rotio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
